# Generated by Django 4.0.1 on 2022-01-26 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zen', '0002_alter_zenarticle_public_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zenarticle',
            name='public_time',
        ),
    ]
