---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

trigger:
  - branch:
      - main

steps:
- name: pytest
  image: python:3.10-bullseye
  environment:
    DB_USER: postgres
    DB_NAME: test
    DB_HOST: postgres
    DB_PORT: 5432
  commands:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install
  - cd app
  - pytest --import-mode=importlib

- name: docker
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: valentinvolkov/content-bulk.online
    tags: latest
---
kind: signature
hmac: 1bfecc3a5dca05021a72681a08b3ae37f884929ccc17fc490fc3b7c05120b849

...
