---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: pytest
  image: python:3.10-bullseye
  environment:
    DB_USER: postgres
    DB_NAME: test
    DB_HOST: postgres
    DB_PORT: 5432
  commands:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install
  - cd app
  - pytest --import-mode=importlib
  when:
    event:
      - pull_request
    branch:
      - main
    action:
      - opened

- name: docker
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: valentinvolkov/content-bulk.online
    tags: latest
  when:
    event:
      - push
    branch:
      - main
---
kind: signature
hmac: af320cd2dfbba0b0d2b9e1c5a51846369a510747e23e4b8aa16af3a32ed972c5

...
