kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: pytest
  image: python:3.10-bullseye
  commands:
  - pip install poetry
  - poetry install
  - cd app
  - pytest --import-mode=importlib

- name: docker
  image: plugins/docker
  settings:
    username: valentinvolkov
    password: uHFVJNFl0
    repo: valentinvolkov/content-bulk.online
    tags: latest