---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: pytest
  image: python:3.10-bullseye
  environment:
    DB_USER: postgres
    DB_NAME: test
    DB_HOST: postgres
    DB_PORT: 5432
  commands:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install
    - cd app
    - pytest --import-mode=importlib
  when:
    branch:
      - development
    event:
      - pull_request
    action:
      - opened

- name: docker
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: valentinvolkov/content-bulk.online
    tags: latest
    when:
      branch:
        - main
      event:
        - push
---
kind: signature
hmac: a78ec39fc9b7cf4497200d7c0d7fb4625f54a1e1ae38aa813cf90e050c23238e

...
