# Generated by Django 4.0.1 on 2022-01-17 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZenArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('link', models.URLField(unique=True, verbose_name='Source link')),
                ('likes', models.IntegerField()),
                ('reads', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('to_parse_interval', models.DurationField()),
                ('public_date', models.DateField()),
                ('public_time', models.TimeField()),
                ('length', models.IntegerField()),
                ('num_images', models.IntegerField()),
                ('audience', models.IntegerField()),
                ('visitors', models.IntegerField()),
                ('read_time', models.DurationField()),
                ('subscribers', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Article',
                'db_table': 'zen_articles',
            },
        ),
        migrations.CreateModel(
            name='ZenFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('users_num', models.IntegerField(verbose_name='Users')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='zen.zenarticle')),
            ],
            options={
                'verbose_name': 'Feed',
                'db_table': 'zen_feeds',
            },
        ),
    ]
