# Generated by Django 4.0.1 on 2022-01-14 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZenArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('link', models.URLField(unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Zen article',
                'db_table': 'zen_article',
            },
        ),
        migrations.CreateModel(
            name='ZenFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('users_num', models.IntegerField(verbose_name='Кол. пользователей')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='zen.zenarticle')),
            ],
            options={
                'verbose_name': 'Zen feed from comments',
            },
        ),
    ]
