# Generated by Django 4.0.1 on 2022-01-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zenarticle',
            options={'verbose_name': 'Article'},
        ),
        migrations.AlterModelOptions(
            name='zenfeed',
            options={'verbose_name': 'Feed'},
        ),
        migrations.AlterField(
            model_name='zenfeed',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Название'),
        ),
    ]
