# Generated by Django 4.0.1 on 2022-01-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zenarticle',
            name='public_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='zenarticle',
            name='public_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='zenarticle',
            name='read_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='zenarticle',
            name='to_parse_interval',
            field=models.IntegerField(),
        ),
    ]
