# Generated by Django 4.0.1 on 2022-01-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zen', '0002_alter_zenarticle_options_alter_zenfeed_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zenarticle',
            name='link',
            field=models.URLField(unique=True, verbose_name='Source link'),
        ),
        migrations.AlterField(
            model_name='zenarticle',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='zenfeed',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='zenfeed',
            name='users_num',
            field=models.IntegerField(verbose_name='Users'),
        ),
    ]
